### ISSUE TITLE
Create sunscreen open script 

### ISSUE THREAD

**Issue by rbisschops** [rbisschops/homeassistant#11]
User story:
When it's not raining and no rain is expected for the coming 60 minutes, open the sunscreen when the sun is above the horizon by xx degrees.

**Comment by rbisschops** [comment]
Added script to development branch in package_garden:
```
  ## Open sunscreen based on position of the sun (elevation)
  - alias: "Zonnescherm uit" 
    hide_entity: false
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        # Can be a positive or negative number
        above: 21.0
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'off'
        - condition: template
          value_template: '{{ states.sensor.rotterdam_precipitation_forecast_total.state |int == 0.0 }}'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.domo_sunscreen

```
 Needs testing.
Also added manual switch to package_miscellaneous:
```
## Sunscreen mode toggle switch, used for setting when sunscreen should stay closed 
## Several automations depend on this
  sunscreen_mode:
    name: Zonnescherm handmatig
    icon: mdi:toggle-switch
    initial: off
```
Requires button on one of the lovelace pages to be added!!
