### ISSUE TITLE
Create sunscreen close script

### ISSUE THREAD

**Issue by rbisschops** [rbisschops/homeassistant#12]
User story: When rain is exepected within x hours or when it's xx:xx hour, close the sunscreen.

**Comment by rbisschops** [comment]
Added script to development branch in package_garden:
```
  ## Close sunscreen when rain is expected (percipitation > 0.0       
  - alias:Zonnescherm in regenverwachting
    hide_entity: false
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:  sensor.rotterdam_precipitation_forecast_total
        value_template: "{{ state.state }}"
        above: 0.0
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.domo_sunscreen
```
Needs to be tested!!
Also need to add sunscreen close automation based on time or sun (azimuth)

**Comment by rbisschops** [comment]
Added support for sunscreen close based on Azimuth (position of the sun)
```
  ## Close sunscreen when rain is expected (percipitation > 0.0 or when azimuth is over 200.0  
  - alias:Zonnescherm in
    hide_entity: false
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.rotterdam_precipitation_forecast_total
        value_template: "{{ state.state }}"
        above: 0.0
      - platform: numeric_state
        entity_id: sensor.rotterdam_precipitation_forecast_total
        value_template: "{{ state.attributes.azimuth }}"
        above: 200.00     
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.domo_sunscreen
```
