### ISSUE TITLE
RAG status for home humidty in the UI

### ISSUE THREAD

**Issue by rbisschops** [rbisschops/homeassistant#25]
### The problem
Add dashboard items for showing the humidity in the house by means of RAG (Red-Amber-Green) indicators. This based on custom button card with grid settings. (see examples https://github.com/custom-cards/button-card#custom-fields) 

### Environment
HA version: 0.107.5
Configuration: 0.9.13
button-card: 3.0.0

### Problem-relevant
None

### Additional information
None

**Comment by rbisschops** [comment]
Added code to ui-lovelace.yaml
```
button_card_templates:
  stats_rh_rag_icon:
    styles:
      card:
        - height: 60px
        - padding: 2%
      name:
        - font-size: 0.9em
        - font-weight: normal
        - text-align: left
decluttering_templates:
  stats_rh_rag_icon_rh:
    card:
      type: custom:button-card
      entity: 'sensor.environment_[[sensor]]_humidity'
      icon: >
        [[[
          if (parseFloat(entity.state) < 40) return 'mdi:alpha-l-circle';
          if (parseFloat(entity.state) < 45 && parseFloat(entity.state) >= 40) return 'mdi:alpha-l-circle';
          if (parseFloat(entity.state) >= 45 && parseFloat(entity.state) <= 55) return 'mdi:alpha-n-circle';
          if (parseFloat(entity.state) > 55 && parseFloat(entity.state) <= 60) return 'mdi:alpha-h-circle';
          if (parseFloat(entity.state) > 60) return 'mdi:alpha-h-circle';
          else return 'mdi:alert-circle';
        ]]]
      template: stats_rh_rag_icon
      name: '[[name]]'
      tap_action:
        action: more-info
      styles:
        grid:
          - grid-template-areas: '"i temp" "n n"'
          - grid-template-columns: 1fr 1fr
          - grid-template-rows: 1fr
        img_cell:
          - justify-content: start
          - align-items: start
          - margin: none
        icon:
          - color: >
             [[[
              if (parseFloat(entity.state) < 40) return 'rgb(216, 0, 0)';
              if (parseFloat(entity.state) < 45 && parseFloat(entity.state) >= 40) return 'rgb(244, 180, 0)';
              if (parseFloat(entity.state) >= 45 && parseFloat(entity.state) <= 55) return 'rgb(56, 150, 56)';
              if (parseFloat(entity.state) > 55 && parseFloat(entity.state) <= 60) return 'rgb(244, 180, 0)';
              if (parseFloat(entity.state) > 60) return 'rgb(216, 0, 0)';
              else return 'rgb(224, 224, 224)';
             ]]]
        custom_fields:
          temp:
            - align-self: start
            - justify-self: end
      custom_fields:
        temp: >
          [[[
            return `<ha-icon
              icon="mdi:water-percent"
              style="width: 12px; height: 1em;">
              </ha-icon><span style="font-size: 0.8em;">${entity.state}%</span>`
          ]]]
```
Added to home.yaml:
```
    - type: custom:decluttering-card
      template: custom_markdown_card_small
      variables:
        - title: Beneden verdieping
    - type: horizontal-stack
      cards:
        - type: custom:decluttering-card
          template: stats_rh_rag_icon_rh
          variables:
            - sensor: livingroom
            - name: Woonkamer
            - icon: water-percent
        - type: custom:decluttering-card
          template: stats_rh_rag_icon_rh
          variables:
            - sensor: toilet
            - name: Toilet
            - icon: water-percent
        - type: custom:decluttering-card
          template: stats_rh_rag_icon_rh
          variables:
            - sensor: storage
            - name: Berging
            - icon: water-percent
```
And two additional horizontal rows for other sensors.
