### ISSUE TITLE
Media buttons not working anymore after custom button-card update

### ISSUE THREAD

**Issue by rbisschops** [rbisschops/homeassistant#33]
After update of version custom-button-card (V0.6 >V1.11.1), the conditional buttons are not working anymore.
```
  media_button_small_text_1:
    card:
      type: custom:button-card
      template: media_button_small_text_1
      name: '[[name]]'
      action: service
      service:
        domain: remote
        action: send_command
        data: 
          entity_id: remote.bisschops
          device: '[[device]]'
          command: '[[command]]'
```
Update needed?
