### ISSUE TITLE
Garden lights not switching on at home coming of at least one individual

### ISSUE THREAD

**Issue by rbisschops** [rbisschops/homeassistant#6]
Garden lights stay out when nobody is home. When someone comes home, the garden lights should switch on under the condition that its after sunset +15 min and that its before 23:00.

**Comment by rbisschops** [comment]
Fix is probably in the after_offset part of the condition. This is a timeslot instead of an offset.
 ```
   condition: and
      conditions:     
        - condition: sun
          after: sunset
          after_offset: "00:15:00"
        - condition: time
          before: '23:00:00'
```
Probably remove the after_offset part.
